steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/prj-croud-dev-beta-platform/open-webui',
    '--build-arg', 'BUILDPLATFORM=linux/amd64',
    '--build-arg', 'NODE_OPTIONS=--max-old-space-size=8192',
    '.'
  ]
  env:
  - 'DOCKER_BUILDKIT=1'
images:
- 'gcr.io/prj-croud-dev-beta-platform/open-webui'